server.port=8585
server.servlet.context-path=/workintech

info.app.name=WorkInTech Application
info.app.description=Demo Spring Boot service configured for Actuator endpoints
info.app.version=1.0.0

management.endpoints.web.exposure.include=health,info,mappings
